In [2]:
#Functions 

In [3]:
def hello():
    """hello"""
    print("Hello")
    print("Glad you meet")
hello()

Hello
Glad you meet


In [4]:
def sq(num):
    result = num *num 
    return result

square = sq(3)
print(square)

9


In [5]:
func = lambda x, y:x+y

In [6]:
x = lambda a: a+10
print(x(5))

15


In [7]:
def calculate_carbon_footprint(energy_consumption, emission_factor):
    return energy_consumption * emission_factor

In [8]:
energy_consumption = 1000
emission_factor = 0.475

carbon_footprint =calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon Footprint: {carbon_footprint} kg CO2")

Carbon Footprint: 475.0 kg CO2


In [9]:
cities = [
    {"name": "City A", "carbon_footprint" :500},
    { "name": "City B", "carbon_footprint" :119},
    { "name": "City C", "carbon_footprint" :504},
    { "name": "City D", "carbon_footprint" :590},
    { "name": "City E", "carbon_footprint" :440}
     ]

sustainable_threshold = 400
sustainable_cities = list(filter(lambda city: city["carbon_footprint"] < sustainable_threshold, cities))

print("Sustainable Cities")
for city in sustainable_cities:
    print(city["name"])
                            



Sustainable Cities
City B


In [10]:
import pandas as pd

#Sample renewable energy sources data
renewable_sources = ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass"]

#Sample green technology project data (for DataFrame)
data = {
    "Prject": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100], # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250], # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [11]:
projects_df = pd.DataFrame(data)
print("Green Technology Project DataFrame:")
projects_df

Green Technology Project DataFrame:


Prject  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [12]:
#access the project column
print("\nList of the Projects:")
print(projects_df["Prject"])


List of the Projects:
0          Solar Farm A
1        Wind Turbine X
2          Hydropower Y
3          Solar Roof Z
4    Geothermal Plant P
Name: Prject, dtype: object


In [13]:
print(projects_df["Technology"])

0         Solar
1          Wind
2    Hydropower
3         Solar
4    Geothermal
Name: Technology, dtype: object


In [14]:
print(projects_df[["Prject","Technology"]])

               Prject  Technology
0        Solar Farm A       Solar
1      Wind Turbine X        Wind
2        Hydropower Y  Hydropower
3        Solar Roof Z       Solar
4  Geothermal Plant P  Geothermal


In [15]:
#Filter projects with cpacity greater than 100 MW
high_capacity_projects = projects_df[projects_df["Capacity (MW)"]>100]
print("\nProjects with capacity greater than 100Mw:")
print(high_capacity_projects)


Projects with capacity greater than 100Mw:
           Prject  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [16]:
#Add a new column for cost per MW
projects_df["Cost per MW"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]
print("\nDataframe with Cost per MW:")
print(projects_df)


Dataframe with Cost per MW:
               Prject  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000  


In [17]:
#Aggregate the total capacity and cost
total_capacity = projects_df["Capacity (MW)"].sum()
total_cost = projects_df["Cost (Million $)"].sum()

print(f"\nTotal Capacity of all projects: {total_capacity} MW")
print(f"Total cost of all projects: ${total_cost} million")


Total Capacity of all projects: 800 MW
Total cost of all projects: $1300 million


In [18]:
#group by 'Technology' and calaculate total capacity for each type
grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("\nTotal capacity by technology:")
print(grouped_data)


Total capacity by technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [19]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a))

[0 1 2 3]
<class 'numpy.ndarray'>
1
(4,)
4


In [20]:
import numpy as np 
mylist = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
e_c = np.array([12,13,14,15,16,25])
print(e_c)

[12 13 14 15 16 25]


In [22]:
mn = np.mean(e_c)
print(f"{mn:.2f}")

15.83


In [23]:
std_deviation = np.std(e_c) # e_c = energy_consumption
print(f"\nStandard devisation of energy consumption: {std_deviation:.2f} MWh")


Standard devisation of energy consumption: 4.30 MWh


In [24]:
reshaped_array = e_c.reshape((6,1))
print("\nReshaped Energy Consumption array (6x1): ")
print(reshaped_array)


Reshaped Energy Consumption array (6x1): 
[[12]
 [13]
 [14]
 [15]
 [16]
 [25]]


In [25]:
import pandas as pd
import numpy as np


# Sample data with missing values
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [1200, 400, np.nan, 150, 250, np.nan],
}

# Create a DataFrame
energy_df = pd.DataFrame(data)

# Display the DataFrame
print("Original Energy Data with Missing Values:")
print(energy_df)

Original Energy Data with Missing Values:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0            1200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN


In [26]:
#Impute missing values in 'Energy Consumption (MWh)' with the mean

energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(), inplace=True)

#Impute missing values in 'Cost (Million $) with the mean

energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean(), inplace=True)

print("\nData After Imputing Missing Values with Mean:")

print(energy_df)


Data After Imputing Missing Values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0            1200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             500.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             500.0


C:\Users\knimj\AppData\Local\Temp\ipykernel_5888\612028636.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(), inplace=True)
C:\Users\knimj\AppData\Local\Temp\ipykernel_5888\612028636.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we a

In [27]:
energy_df["Missing Consumption"] = energy_df["Energy Consumption (MWh)"].isna().astype(int)

print("\nData with Missing Values Flagged:")

print(energy_df)


Data with Missing Values Flagged:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                    1200.0            1200.0   
1          Wind                    2450.0             400.0   
2    Hydropower                    2900.0             500.0   
3    Geothermal                    2450.0             150.0   
4       Biomass                    2500.0             250.0   
5       Nuclear                    3200.0             500.0   

   Missing Consumption  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    0  


In [28]:
from sklearn.preprocessing import MinMaxScaler

#Normalize the 'Energy Consumption (MWh) and "Cost (Million $)'

scaler = MinMaxScaler()

energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] = scaler.fit_transform(

energy_df [["Energy Consumption (MWh)", "Cost (Million $)"]]

)

print("\nData After Normalization (Min-Max Scaling):")

print(energy_df)


Data After Normalization (Min-Max Scaling):
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                     0.000          1.000000   
1          Wind                     0.625          0.238095   
2    Hydropower                     0.850          0.333333   
3    Geothermal                     0.625          0.000000   
4       Biomass                     0.650          0.095238   
5       Nuclear                     1.000          0.333333   

   Missing Consumption  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    0  


In [29]:
from sklearn.preprocessing import StandardScaler

# Standardize the 'Energy Consumption (MWh)' and 'Cost (Million $)'

scaler = StandardScaler()

energy_df [["Energy Consumption (MWh)", "Cost (Million $)"]] =scaler.fit_transform(

energy_df [["Energy Consumption (MWh)", "Cost (Million $)"]]

)

print("\nData After Standardization (Z-score Scaling):")

print(energy_df)


Data After Standardization (Z-score Scaling):
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar             -2.005893e+00          2.071707   
1          Wind              3.563181e-16         -0.295958   
2    Hydropower              7.221213e-01          0.000000   
3    Geothermal              3.563181e-16         -1.035854   
4       Biomass              8.023570e-02         -0.739895   
5       Nuclear              1.203536e+00          0.000000   

   Missing Consumption  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    0  


In [30]:
# One-hot encode the 'Energy Source' column

energy_encoded_df = pd.get_dummies (energy_df, columns=["Energy Source"])

print("\nData After One-Hot Encoding Categorical Variables:")

print(energy_encoded_df)


Data After One-Hot Encoding Categorical Variables:
   Energy Consumption (MWh)  Cost (Million $)  Missing Consumption  \
0             -2.005893e+00          2.071707                    0   
1              3.563181e-16         -0.295958                    0   
2              7.221213e-01          0.000000                    0   
3              3.563181e-16         -1.035854                    0   
4              8.023570e-02         -0.739895                    0   
5              1.203536e+00          0.000000                    0   

   Energy Source_Biomass  Energy Source_Geothermal  Energy Source_Hydropower  \
0                  False                     False                     False   
1                  False                     False                     False   
2                  False                     False                      True   
3                  False                      True                     False   
4                   True                     False       

In [31]:
# Create a new feature: Energy Consumption per Million $
energy_df["Consumption per $Million"] = energy_df["Energy Consumption (MWh)"] / energy_df["Cost (Million $)"]

print("\nData with New Feature (Consumption per $Million):")
print(energy_df)


Data with New Feature (Consumption per $Million):
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar             -2.005893e+00          2.071707   
1          Wind              3.563181e-16         -0.295958   
2    Hydropower              7.221213e-01          0.000000   
3    Geothermal              3.563181e-16         -1.035854   
4       Biomass              8.023570e-02         -0.739895   
5       Nuclear              1.203536e+00          0.000000   

   Missing Consumption  Consumption per $Million  
0                    0             -9.682317e-01  
1                    0             -1.203948e-15  
2                    0                       inf  
3                    0             -3.439850e-16  
4                    0             -1.084420e-01  
5                    0                       inf  
